name: github_graphql_api
description: A new Flutter project to explore Github GraphQL API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  graphql: 5.1.1
  graphql_flutter: 5.1.0
  shared_preferences: 2.0.20

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

flutter:
  uses-material-design: true
